on:
  push:
    branches:
      - master
  pull_request:

name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - run: |
          ./scripts/check-bases

      - run: |
          ./scripts/check-variants

      - run: |
          ./scripts/check-builds
