on:
  push:
    branches:
      - master
  pull_request:

name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - run: |
          ./scripts/check-bases

      - run: |
          ./scripts/check-variants

      - run: |
          ./scripts/check-builds
